// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlc4f5cXxflUw9QAE_ii6qF6f1viEY-bo',
    appId: '1:83815383219:web:7c88c7ab740bba0ae5f0c6',
    messagingSenderId: '83815383219',
    projectId: 'multivendor-39a0a',
    authDomain: 'multivendor-39a0a.firebaseapp.com',
    storageBucket: 'multivendor-39a0a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOo7tIsoPtpHOFfgy9dk3jzJJF-6lFOJM',
    appId: '1:83815383219:android:3aca6c43c15340e7e5f0c6',
    messagingSenderId: '83815383219',
    projectId: 'multivendor-39a0a',
    storageBucket: 'multivendor-39a0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBqbv5kku-LC13O22tCNwSzHYiq3TBA4',
    appId: '1:83815383219:ios:2f45de6b6a466b08e5f0c6',
    messagingSenderId: '83815383219',
    projectId: 'multivendor-39a0a',
    storageBucket: 'multivendor-39a0a.firebasestorage.app',
    iosBundleId: 'com.example.multiVenors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXBqbv5kku-LC13O22tCNwSzHYiq3TBA4',
    appId: '1:83815383219:ios:2f45de6b6a466b08e5f0c6',
    messagingSenderId: '83815383219',
    projectId: 'multivendor-39a0a',
    storageBucket: 'multivendor-39a0a.firebasestorage.app',
    iosBundleId: 'com.example.multiVenors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlc4f5cXxflUw9QAE_ii6qF6f1viEY-bo',
    appId: '1:83815383219:web:4d3ee5122e6033f3e5f0c6',
    messagingSenderId: '83815383219',
    projectId: 'multivendor-39a0a',
    authDomain: 'multivendor-39a0a.firebaseapp.com',
    storageBucket: 'multivendor-39a0a.firebasestorage.app',
  );
}
